### ISSUE TITLE
Watcher drops when writing YAML

### ISSUE THREAD

**Issue by yousan** [moon0326/swagger-ui-watcher#25]
I appreciate watcher, it helps me a lot. I don't have to re-generate spec file.

swagger-ui-watcher drops when writing YAML file.
It is NOT completed YAML. (At writing)

```
/usr/local/lib/node_modules/swagger-ui-watcher/node_modules/js-yaml/lib/js-yaml/loader.js:171
  throw generateError(state, message);
  ^
YAMLException: can not read an implicit mapping pair; a colon is missed at line 66, column 17:
            CategoryName
                    ^
    at generateError (/usr/local/lib/node_modules/swagger-ui-watcher/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/usr/local/lib/node_modules/swagger-ui-watcher/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readBlockMapping (/usr/local/lib/node_modules/swagger-ui-watcher/node_modules/js-yaml/lib/js-yaml/loader.js:1037:11)
    at composeNode (/usr/local/lib/node_modules/swagger-ui-watcher/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockMapping (/usr/local/lib/node_modules/swagger-ui-watcher/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/usr/local/lib/node_modules/swagger-ui-watcher/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockMapping (/usr/local/lib/node_modules/swagger-ui-watcher/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/usr/local/lib/node_modules/swagger-ui-watcher/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockMapping (/usr/local/lib/node_modules/swagger-ui-watcher/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/usr/local/lib/node_modules/swagger-ui-watcher/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
```

After watcher drops, restart watcher manually.
Any ideas?

**Comment by vpmv** [comment]
This is essentially what I meant by #24

**Comment by moon0326** [comment]
@yousan Can you please provide your sample files? It's hard to test without sample files.

**Comment by yousan** [comment]
Sorry I got I thought I made a duplicated issue ;)


This is a sample, `get: hoge` (Yes, it is invalid)  was saved on a way of editing.

```
paths:
  /getItem:
    get: hoge
      tags:
        - item
```

Then watcher got error.

```
$ swagger-ui-watcher specs/sample.yaml
Listening on http://127.0.0.1:8000
File changed. Sent updated spec to the browser.

/usr/local/lib/node_modules/swagger-ui-watcher/node_modules/js-yaml/lib/js-yaml/loader.js:171
  throw generateError(state, message);
  ^
YAMLException: bad indentation of a mapping entry at line 39, column 11:
          tags:
```

Here is the version.

```
$(npm bin)/swagger-ui-watcher --version
2.1.4
```

**Comment by moon0326** [comment]
@yousan could you give me a testable file? It's hard to understand what the problem is with your sample. Your original post has the following error.

```
YAMLException: can not read an implicit mapping pair; a colon is missed at line 66, column 17:
            CategoryName
```

Your latest post has 

```
YAMLException: bad indentation of a mapping entry at line 39, column 11:
          tags:
```

they are two different errors.

It would be much easier if you post a file that produces the same output.

Thanks,
Moon

**Comment by moon0326** [comment]
closing it for now due to inactivity. Please re-open if necessary.

**Comment by yousan** [comment]
@moon0326 
Sorry I am late.
Here is the sample (and incomplete) spec file.
In this case, "tags: hoge" is invalid.

Watching the file and broke yaml, then watcher drops.

```
openapi: "3.0.0"
info:
  description: "hello"
  version: 1.1.3
  title: sample
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://example.com
    description: 本番サーバ
tags:
- name: item
  description: 商品
- name: category
  description: 商品カテゴリ
- name: pet
  description: Everything about your Pets
  externalDocs:
    description: Find out more
    url: http://swagger.io
- name: store
  description: Access to Petstore orders
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
paths:
  /getItem:
    get:
      tags: hoge
      - item
```
