### ISSUE TITLE
just write paths like '/test' and no other properties cause exit

### ISSUE THREAD

**Issue by shaunxq** [moon0326/swagger-ui-watcher#3]
/usr/lib/node_modules/swagger-ui-watcher/node_modules/_js-yaml@3.10.0@js-yaml/lib/js-yaml/loader.js:171
  throw generateError(state, message);
  ^
YAMLException: can not read an implicit mapping pair; a colon is missed at line 264, column 6:
      '/'
         ^
    at generateError (/usr/lib/node_modules/swagger-ui-watcher/node_modules/_js-yaml@3.10.0@js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/usr/lib/node_modules/swagger-ui-watcher/node_modules/_js-yaml@3.10.0@js-yaml/lib/js-yaml/loader.js:171:9)
    at readBlockMapping (/usr/lib/node_modules/swagger-ui-watcher/node_modules/_js-yaml@3.10.0@js-yaml/lib/js-yaml/loader.js:1037:11)
    at composeNode (/usr/lib/node_modules/swagger-ui-watcher/node_modules/_js-yaml@3.10.0@js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockMapping (/usr/lib/node_modules/swagger-ui-watcher/node_modules/_js-yaml@3.10.0@js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/usr/lib/node_modules/swagger-ui-watcher/node_modules/_js-yaml@3.10.0@js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/usr/lib/node_modules/swagger-ui-watcher/node_modules/_js-yaml@3.10.0@js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/usr/lib/node_modules/swagger-ui-watcher/node_modules/_js-yaml@3.10.0@js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (/usr/lib/node_modules/swagger-ui-watcher/node_modules/_js-yaml@3.10.0@js-yaml/lib/js-yaml/loader.js:1569:19)
    at Object.safeLoad (/usr/lib/node_modules/swagger-ui-watcher/node_modules/_js-yaml@3.10.0@js-yaml/lib/js-yaml/loader.js:1591:10)

**Comment by moon0326** [comment]
@shaunxq Thank you for reporting the issue. I will look into it over the weekend. Thanks!

**Comment by moon0326** [comment]
@shaunxq Hi, so sorry. I almost forgot about this open issue. What was your exact syntax? Could you copy and paste? I was not able to replicate it.

**Comment by moon0326** [comment]
closing it as there is no response.
